apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ps-docker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJwc2RldmVsb3BlciIsInBhc3N3b3JkIjoiRkJ2QWdmRkhWOGs4ZUhVaCIsImVtYWlsIjoiZGV2ZWxvcGVyQHByb2dyZXNzb2Z0LmlvIiwiYXV0aCI6ImNITmtaWFpsYkc5d1pYSTZSa0oyUVdkbVJraFdPR3M0WlVoVmFBPT0ifX19