{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "oracle-standalone11g.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oracle-standalone11g.name" . }}
    helm.sh/chart: {{ include "oracle-standalone11g.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
 {{- if eq .Values.persistence.storageClass "oci" }}
  selector:
    matchLabels:
      failure-domain.beta.kubernetes.io/zone: {{ .Values.persistence.ad }}
	  {{- end }}
{{- end }}
