apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-standalone11g.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oracle-standalone11g.name" . }}
    helm.sh/chart: {{ include "oracle-standalone11g.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: {{ include "oracle-standalone11g.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
