#!/bin/bash
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2018 Oracle and/or its affiliates. All rights reserved.
# 
# Since: November, 2016
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle Database based on following parameters:
#              $ORACLE_SID: The Oracle SID and CDB name
#              $ORACLE_PDB: The PDB name
#              $ORACLE_PWD: The Oracle password
# 
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
# 

set -e

# Check whether ORACLE_SID is passed on
export ORACLE_SID=${1:-EE}

# Check whether ORACLE_PDB is passed on
export ORACLE_PDB=${2:-EE1}

# Auto generate ORACLE PWD if not passed on
export ORACLE_PWD=oracle
echo "ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: $ORACLE_PWD";

# Replace place holders in response file
cp $ORACLE_BASE/$CONFIG_RSP $ORACLE_BASE/dbca.rsp
sed -i -e "s|###ORACLE_SID###|$ORACLE_SID|g" $ORACLE_BASE/dbca.rsp
sed -i -e "s|###ORACLE_PDB###|$ORACLE_PDB|g" $ORACLE_BASE/dbca.rsp
sed -i -e "s|###ORACLE_PWD###|$ORACLE_PWD|g" $ORACLE_BASE/dbca.rsp
sed -i -e "s|###ORACLE_CHARACTERSET###|$ORACLE_CHARACTERSET|g" $ORACLE_BASE/dbca.rsp

# If there is greater than 8 CPUs default back to dbca memory calculations
# dbca will automatically pick 40% of available memory for Oracle DB
# The minimum of 2G is for small environments to guarantee that Oracle has enough memory to function
# However, bigger environment can and should use more of the available memory
# This is due to Github Issue #307
if [ `nproc` -gt 8 ]; then
   sed -i -e "s|totalMemory=2048||g" $ORACLE_BASE/dbca.rsp
fi;

# Create network related config files (sqlnet.ora, tnsnames.ora, listener.ora)
mkdir -p $ORACLE_HOME/network/admin
echo "NAME.DIRECTORY_PATH= (TNSNAMES, EZCONNECT, HOSTNAME)" > $ORACLE_HOME/network/admin/sqlnet.ora

# Listener.ora
echo "LISTENER = 
(DESCRIPTION_LIST = 
  (DESCRIPTION = 
    (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1)) 
    (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521)) 
  ) 
) 

DEDICATED_THROUGH_BROKER_LISTENER=ON
DIAG_ADR_ENABLED = off
" > $ORACLE_HOME/network/admin/listener.ora

# Start LISTENER and run DBCA
lsnrctl start &&
dbca -silent -createDatabase -responseFile $ORACLE_BASE/dbca.rsp ||
 cat /opt/oracle/cfgtoollogs/dbca/$ORACLE_SID/$ORACLE_SID.log ||
 cat /opt/oracle/cfgtoollogs/dbca/$ORACLE_SID.log

echo "$ORACLE_SID=localhost:1521/$ORACLE_SID" > $ORACLE_HOME/network/admin/tnsnames.ora
echo "$ORACLE_PDB= 
  (DESCRIPTION = 
    (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = $ORACLE_PDB)
    )
  )" >> $ORACLE_HOME/network/admin/tnsnames.ora

# Remove second control file, fix local_listener, make PDB auto open, enable EM global port
sqlplus / as sysdba << EOF
   ALTER SYSTEM SET control_files='$ORACLE_BASE/oradata/$ORACLE_SID/control01.ctl' scope=spfile;
   ALTER SYSTEM SET local_listener='';
   ALTER PLUGGABLE DATABASE $ORACLE_PDB SAVE STATE;
   EXEC DBMS_XDB_CONFIG.SETGLOBALPORTENABLED (TRUE);

   ALTER SYSTEM SET processes=900 scope=spfile;
   ALTER SYSTEM SET sessions=900 scope=spfile;
   ALTER SYSTEM SET sga_target=4G scope=spfile;
   ALTER SYSTEM SET pga_aggregate_target=1G scope=spfile;


alter system set db_securefile ='ALWAYS';
/
alter system set DB_16K_CACHE_SIZE = 350m;
/
PROMPT Creating Tablespace 'SEC_TAB01'
CREATE TABLESPACE SEC_TAB01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/SEC_TAB01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'SEC_IDX01'
CREATE TABLESPACE SEC_IDX01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/SEC_IDX01.dbf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'SEC_LOG_TAB01'
CREATE TABLESPACE SEC_LOG_TAB01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/SEC_LOG_TAB01.dbf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'ECC_TAB01'
CREATE TABLESPACE ECC_TAB01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_TAB01.dbf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'ECC_TAB02'
CREATE TABLESPACE ECC_TAB02
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_TAB02.dbf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'ECC_HIST_TAB01'
CREATE TABLESPACE ECC_HIST_TAB01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_HIST_TAB01.dbf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'ECC_IDX01'
CREATE TABLESPACE ECC_IDX01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_IDX01.dbf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'ECC_HIST_IDX01'
CREATE TABLESPACE ECC_HIST_IDX01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_HIST_IDX01.dbf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'ECC_HIST_LOB01'
CREATE TABLESPACE ECC_HIST_LOB01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_HIST_LOB01.dbf'  SIZE 100M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 32M
BLOCKSIZE 16K
/
PROMPT Creating Tablespace 'ECC_HIST_LOB02'
CREATE TABLESPACE ECC_HIST_LOB02
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_HIST_LOB02.dbf'  SIZE 100M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 32M
BLOCKSIZE 16K
/
PROMPT Creating Tablespace 'ECC_HIST_LOB03'
CREATE TABLESPACE ECC_HIST_LOB03
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_HIST_LOB03.pdf'  SIZE 100M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 32M
BLOCKSIZE 16K
/
PROMPT Creating Tablespace 'ECC_HIST_LOB04'
CREATE TABLESPACE ECC_HIST_LOB04
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_HIST_LOB04.pdf'  SIZE 100M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 32M
BLOCKSIZE 16K
/
PROMPT Creating Tablespace 'ECC_LOB01'
CREATE TABLESPACE ECC_LOB01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_LOB01.pdf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 4M
BLOCKSIZE 16K
/
PROMPT Creating Tablespace 'ECC_LOB02'
CREATE TABLESPACE ECC_LOB02
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_LOB02.pdf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 4M
BLOCKSIZE 16K
/
PROMPT Creating Tablespace 'ECC_INT_IDX01'
CREATE TABLESPACE ECC_INT_IDX01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_INT_IDX01.pdf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'ECC_INT_TAB01'
CREATE TABLESPACE ECC_INT_TAB01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_INT_TAB01.pdf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
PROMPT Creating Tablespace 'ECC_LOG_IDX01'
CREATE TABLESPACE ECC_LOG_IDX01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_LOG_IDX01.pdf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
NOLOGGING
/
PROMPT Creating Tablespace 'ECC_LOG_TAB01'
CREATE TABLESPACE ECC_LOG_TAB01
DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/ECC_LOG_TAB01.pdf'  SIZE 50M AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/



   exit;
EOF

# Remove temporary response file
rm $ORACLE_BASE/dbca.rsp
