apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oracle-application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: sierra
        valuesfile: sierra_values.yaml
      - namespace: ecc-sudan
        valuesfile: ecc-sudan_values.yaml
  template:      
    metadata:
      name: '{{namespace}}-oracledb'
    spec:
      project: default
      source:
        repoURL: https://github.com/AceVII/database.git
        targetRevision: HEAD
        path:  ./oracle-standalone19c/oracle-standalone19c
        helm:
        valueFiles:
          - https://github.com/AceVII/database/blob/master/oracle-standalone19c/oracle-standalone19c/ecc-sudan_values.yaml 
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      